var myName="Yogesh";
console.log("Welcome Mr." + myName);
console.log("Length is - " + myName.length);
console.log("Char at 3 - " + myName.charAt(3));
console.log("Concat - " + myName.concat(" From Nagore"));
console.log("Ending with  h:"+ myName.endsWith("h"));
console.log("Starts with Y:"+myName.startsWith("Y"));
console.log(myName.toLowerCase());
console.log(myName.toUpperCase());
console.log("position of o:"+myName.indexOf('o'));

 var today=new Date();
 console.log("Today's Date - " + today);
 console.log(today.getDate());
 console.log(today.getDay());
 console.log(today.getFullYear());
 console.log(today.getYear());
 console.log(today.getHours());
 console.log(today.getMinutes());
 console.log(today.getSeconds());
